<a href="https://colab.research.google.com/github/alimoorreza/CS167-sp25-notes/blob/main/Day14_Project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CS167: Day14
## Project #1

#### CS167: Machine Learning, Spring 2025


📜 [Syllabus](https://analytics.drake.edu/~reza/teaching/cs167_sp25/cs167_syllabus_sp25.pdf)

# Admin Stuff

You should be working on:
- **[Project #1](https://github.com/alimoorreza/CS167-SP25-Project-1)** is released, **Due Monday, April 7th, by 11:59pm**
- You have 2 weeks to finish Project #1

## Models we've talked about so far:

#### k Nearest Neighbors:
- [`sklearn.neighbors.KNeighborsClassifier()`](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html)
- [`sklearn.neighbors.KNeighborsRegressor()`](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html)

#### Weighted k-Nearest-Neighbors:
- [`sklearn.neighbors.KNeighborsClassifier(n_neighbors=5, weights='distance')`](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html)
- [`sklearn.neighbors.KNeighborsRegressor(n_neighbors=5, weights='distance')`](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html)

Change $n\_neighbors=5$ for different experiments but always keep $weights=`distance'$ so that you can invoke the weighted kNN version.

#### Decision Trees:
- [`sklearn.tree.DecisionTreeClassifier()`](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html)
- [`sklearn.tree.DecisionTreeRegressor()`](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html)

#### Random Forests:
- [`sklearn.ensemble.RandomForestClassifier()`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html)
- [`sklearn.ensemble.RandomForestRegressor()`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForesRegressor.html)

## Dummy Variables:
When you need to convert categorical variables to numeric variables, [`pd.get_dummies()`](https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html) is a really helpful function.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
path = '/content/drive/MyDrive/cs167_sp25/datasets/titanic.csv'
titanic = pd.read_csv(path)
print('titanic dataset shape: ', titanic.shape)
titanic.head()

titanic dataset shape:  (891, 15)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

### Things to Notice: `pd.get_dummies()`
- `deck`, `sex`, and `embarked` used to be categorical variables, but they no longer exist in `titanic_dummies`
- instead, we have `deck_A`, `deck_B`, or `embarked_C`, `embarked_Q`, etc.
- when we call `pd.get_dummies()`, we pass in the original dataframe, and the columns we want to convert
- `pd.get_dummies()` returns a new dataframe without the categorical columns.

In [ ]:
titanic_dummies = pd.get_dummies(titanic, columns=['embarked', 'deck'])
titanic_dummies.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,...,embarked_C,embarked_Q,embarked_S,deck_A,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G
0,0,3,male,22.0,1,0,7.2500,Third,man,True,...,0,0,1,0,0,0,0,0,0,0
1,1,1,female,38.0,1,0,71.2833,First,woman,False,...,1,0,0,0,0,1,0,0,0,0
2,1,3,female,26.0,0,0,7.9250,Third,woman,False,...,0,0,1,0,0,0,0,0,0,0
3,1,1,female,35.0,1,0,53.1000,First,woman,False,...,0,0,1,0,0,1,0,0,0,0
4,0,3,male,35.0,0,0,8.0500,Third,man,True,...,0,0,1,0,0,0,0,0,0,0

In [ ]:
titanic_dummies.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'class',
       'who', 'adult_male', 'embark_town', 'alive', 'alone', 'embarked_C',
       'embarked_Q', 'embarked_S', 'deck_A', 'deck_B', 'deck_C', 'deck_D',
       'deck_E', 'deck_F', 'deck_G'],
      dtype='object')

# Project #1: Choose Your Own Machine Learning Adventure

10% of your final grade

__Due__: *Monday, October 7th, by 11:59pm*

[Github Link](https://github.com/alimoorreza/CS167-SP25-Project-1)

## Learning Objectives:

For this project, you will use the scikit-learn library to conduct a machine learning experiment, and your write-up will ask you to explain what you did and interpret the results.

This directly addresses two of the course learning objectives stated in the syllabus:
- Students will be able to create software which utilizes machine learning programming libraries in order to conduct machine-learning-based data analysis.
- Students will be able to develop and conduct machine-learning-based data analysis experiments, and they will be able to interpret and explain the results.

## Project Description:

For this project, you are to identify the dataset you would like to utilize. I have provided several examples in class, but you have the option of using any dataset you can find.

You will be assessed on your ability to utilize algorithms and tools introduced in this class. There are some basic guidelines as to what I want to see laid out below, but you are the machine learning engineer and it is your job to draw some meaningful conclusions about the data.

## Dataset Choice:
For this project, you will get to choose what dataset you use. The ones we've used in class (other than Iris/Titanic/Restaurant as they're pretty small) are all fair game (pokemon, wine quality, breast cancer, spotify). I'd recommend choosing a dataset that is interesting to you--it will make the project more fun and engaging.

Here are some other possibilities--[Kaggle](https://www.kaggle.com/datasets) has many many more, as well as the [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php). It is a good idea to double check with me before grabbing a dataset that's not listed here:
- 🥑 [Avocado Prices](https://www.kaggle.com/datasets/neuromusic/avocado-prices)
- 🎟️ [Admission to University](https://www.kaggle.com/datasets/akshaydattatraykhare/data-for-admission-in-the-university)
- 🏎️ [Speed Dating](https://www.kaggle.com/datasets/whenamancodes/speed-dating)
- 🎓 [World University Ranking](https://www.kaggle.com/datasets/whenamancodes/world-university-ranking-2022-2023)
- 📸 [Top Instagram Influencers](https://www.kaggle.com/datasets/whenamancodes/top-200-influencers-crushing-on-instagram)
- 🌦️ [Weather Prediction](https://www.kaggle.com/datasets/thedevastator/weather-prediction)
- 🎵 [Spotify Recommendation](https://www.kaggle.com/datasets/bricevergnou/spotify-recommendation)
- 🤑 [Student Monthly Expenses](https://www.kaggle.com/datasets/shariful07/nice-work-thanks-for-share)
- 🍺 [Student Alcohol Consumption](https://www.kaggle.com/datasets/uciml/student-alcohol-consumption)
- 🏫 [College Score Card](https://www.kaggle.com/datasets/thedevastator/u-s-department-of-education-college-scorecard-da)
- 🎮 [IMDB Video Games](https://www.kaggle.com/datasets/muhammadadiltalay/imdb-video-games)

✨**New**✨: At the very top of your notebook, I'm asking that in a text cell, you **describe how many points you attempted to get from this project**. Tell me what you think you deserve on this notebook given the rubric:

**Self-Evaluation:**

| **Description/Writing** | **I think I deserve** |
|-------------------------|-----------------------|
| 1: Problem              | /2                    |
| 2: Data Prep            | /2                    |
| 3: Research             | /10                   |
| 4: Analysis             | /10                   |
| 5: Bumps in the Road.   | /1                    |
| Total                   | /25                   |

## Project Expectations: ☑️

You will create a Colab notebook that includes your code and results to document your experiment. Most importantly, **you will use text cells in the notebook to explain what you did, interpret the results, and make your recommendations**.

The written markdown protions must include the following things:

1. **Problem** [2 points]: State the problem you are trying to solve with this machine learning experiment. Include a description of the data, where you got the data, and what you're trying to predict. Is the problem a regression or a classification? What kind of metric do you plan to use to measure the performance of your model?

2.  **Data Preparation** [2 points]: Explain your data preparation. What did you have to do to get your data in shape for your experiments? Why are you certain that you data is clean and prepared for use in your algorithms?

3.  **Research** [10 points]: Put your code and your experiments here.
    - Your research should include using the models that we've talked about in class so far--namely, a K Nearest Neighbors, weighted kNN, Decision Tree, Random Forest, as well as tuning these models (with visuals, i.e. graphs) to find the parameters that give you the best performance using an appropriate metric.
    - Does normalizing your data lead to better performance? If so, why?

4.  **Analysis** [10 points]: What did you discover? What insights/recommendations do you have? What did you find that was interesting? Which model was your best model, which models didn't work well? Why do you think this is? In general, I want a discussion of your experiment, the results, and what they mean.

5.  **Bumps in the Road** [1 point]: What challenges did you encounter? How did you overcome these challenges?

## More Details:

For full credit, your experiments should include the following models:
- __k Nearest Neighbors__
- __weighted k Nearest Neighbors__
- __decision tree__
- __random forest__

You need to demonstrate the performance of these models on both __normalized__ and __non-normalized__ data.

For each of the above models, you need to include a __graph of at least 1 tuned parameter__.

Essentailly, you will be able to fill out this chart with your results:

| **Model**     | **Non-Normalized** | **Normalized** | **Parameter Tuned** |
|---------------|--------------------|----------------|---------------------|
| kNN           |                    |                |                     |
| w-kNN         |                    |                |                     |
| decision tree |                    |                |                     |
| random forest |                    |                |                     |

## Please, cite your sources

If you choose to use code that has not been provided to you in this class, please cite where you got the code from. A simple comment with the URL will suffice.

This is especially true if you are choosing to use a dataset from Kaggle. There are lots of example notebooks for most Kaggle datasets, and while it's totally fine to look at these, using code from these notebooks without citing where you got it from could result in an academic integretity violation.

# Tips on getting started:

Start by answering the questions that you can answer before you even start coding. Look at the datasets and decide which one you want to use.

Use the template for building and testing a scikit-learn model. Start by doing the following:
- Change the example code to work with your new data
- Look for the appropriate documentation for the scikit-learn modules for the machine learning algorithms we have discussed in class.
- Try to produce a plot like the one you did in Notebook 3, but use sklearn like in the example for random forests